name: Autograding Tests
on:
  - push
  - workflow_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  autograding:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # - name: python1 Test
      #   id: python2-test
      #   uses: education/autograding-io-grader@v1
      #   with:
      #     test-name: test1.py
      #     setup-command: sudo -H pip3 install pytest
      #     command: "python test1.py"
      #     # input: hello
      #     # expected-output: HELLO
      #     # comparison-method: exact
      #     timeout: 10
      #     max-score: 20
      - name: A python1 test
        id: a-python1-test
        uses: education/autograding-command-grader@v1
        with:
          test-name: test1.py
          setup-command: sudo -H pip3 install pytest
          command: python test1.py
          timeout: 10
          max-score: 20
      # - name: Python test
      #   id: python-test
      #   uses: education/autograding-python-grader@v1
      # - name: Python test with score
      #   id: python-test-with-score
      #   uses: education/autograding-python-grader@v1
      #   with:
      #     max-score: 30
      - name: Autograding Reporter
        uses: education/autograding-grading-reporter@v1
        env:
          PROGRAM1-PY_RESULTS: "${{steps.program1-py.outputs.result}}"
          PROGRAM2-PY_RESULTS: "${{steps.program2-py.outputs.result}}"
        with:
          runners: "program1-py, program2-py"
